In [1]:
import pandas as pd

#define files
cy_2020 = "202005-citibike-tripdata.csv"
# cy_2021 = "202105-citibike-tripdata.csv"

In [2]:
#make pdframes
cy_may20_df = pd.read_csv(cy_2020)
# cy_may21_df = pd.read_csv(cy_2021)

In [3]:
cy_may20_df.head(5)

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,336,2020-05-01 00:01:06.3380,2020-05-01 00:06:42.9560,2017,E 43 St & 2 Ave,40.750224,-73.971214,465,Broadway & W 41 St,40.755136,-73.986580,18015,Subscriber,1993,1
1,853,2020-05-01 00:01:08.1950,2020-05-01 00:15:21.2150,3376,E 65 St & 2 Ave,40.764719,-73.962221,478,11 Ave & W 41 St,40.760301,-73.998842,35905,Subscriber,1989,1
2,78,2020-05-01 00:01:08.5260,2020-05-01 00:02:27.0490,396,Lefferts Pl & Franklin Ave,40.680342,-73.955769,3789,Fulton St & Irving Pl,40.681860,-73.959432,33350,Subscriber,1938,2
3,1185,2020-05-01 00:02:22.4380,2020-05-01 00:22:08.1220,3630,Frederick Douglass Blvd & W 115 St,40.803865,-73.955931,3506,Lexington Ave & E 120 St,40.801307,-73.939817,43790,Subscriber,1996,1
4,272,2020-05-01 00:02:32.8280,2020-05-01 00:07:05.0880,3776,Central Ave & Starr Street,40.700003,-73.928340,3068,Humboldt St & Varet St,40.703172,-73.940636,39912,Subscriber,1993,1

In [4]:
#may 2021
cy_2021 = "202105-citibike-tripdata.csv"
cy_may21_df = pd.read_csv(cy_2021)

C:\Users\Julio\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (5,7) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [5]:
cy_may21_df.head(5)

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,E12103A91226099A,docked_bike,2021-05-06 17:25:01,2021-05-06 17:45:25,Broadway & W 60 St,6948.11,1 Ave & E 78 St,7020.09,40.769155,-73.981918,40.771404,-73.953517,member
1,26A3DC47FE0EA3A3,docked_bike,2021-05-13 12:48:08,2021-05-13 13:07:37,Broadway & W 25 St,6173.08,E 2 St & Avenue B,5515.02,40.742868,-73.989186,40.722174,-73.983688,member
2,A99F2E1D627B088F,docked_bike,2021-05-16 08:30:13,2021-05-16 08:45:47,46 Ave & 5 St,6286.02,34th Ave & Vernon Blvd,6873.01,40.747310,-73.954510,40.765354,-73.939863,member
3,43E79A45997B7390,docked_bike,2021-05-01 08:38:14,2021-05-01 08:54:27,46 Ave & 5 St,6286.02,34th Ave & Vernon Blvd,6873.01,40.747310,-73.954510,40.765354,-73.939863,member
4,8B3CC649F4F58816,docked_bike,2021-05-09 08:12:31,2021-05-09 08:27:05,46 Ave & 5 St,6286.02,34th Ave & Vernon Blvd,6873.01,40.747310,-73.954510,40.765354,-73.939863,member

In [44]:
start_stop_0520_group = cy_may20_df.groupby(["start station name","end station name","end station latitude","end station longitude"])
start_stop_0520_group.count().head(10)

                                                                                                     tripduration  \
start station name end station name                      end station latitude end station longitude
1 Ave & E 110 St   1 Ave & E 110 St                      40.792327            -73.938300                      200
                   1 Ave & E 18 St [temporarily removed] 40.733812            -73.980544                        1
                   1 Ave & E 5 St                        40.725864            -73.986389                        1
                   1 Ave & E 62 St                       40.761227            -73.960940                        8
                   1 Ave & E 68 St                       40.765005            -73.958185                       11
                   1 Ave & E 78 St                       40.771404            -73.953517                        8
                   1 Ave & E 94 St                       40.781721            -73.945940                       16
                   1 Pl & Clinton St                     40.680959            -73.999057                        1
                   12 Ave & W 125 St                     40.818299            -73.960405                        3
                   12 Ave & W 40 St                      40.760875            -74.002777                        1

                                                                                                     starttime  \
start station name end station name                      end station latitude end station longitude
1 Ave & E 110 St   1 Ave & E 110 St                      40.792327            -73.938300                   200
                   1 Ave & E 18 St [temporarily removed] 40.733812            -73.980544                     1
                   1 Ave & E 5 St                        40.725864            -73.986389                     1
                   1 Ave & E 62 St                       40.761227            -73.960940                     8
                   1 Ave & E 68 St                       40.765005            -73.958185                    11
                   1 Ave & E 78 St                       40.771404            -73.953517                     8
                   1 Ave & E 94 St                       40.781721            -73.945940                    16
                   1 Pl & Clinton St                     40.680959            -73.999057                     1
                   12 Ave & W 125 St                     40.818299            -73.960405                     3
                   12 Ave & W 40 St                      40.760875            -74.002777                     1

                                                                                                     stoptime  \
start station name end station name                      end station latitude end station longitude
1 Ave & E 110 St   1 Ave & E 110 St                      40.792327            -73.938300                  200
                   1 Ave & E 18 St [temporarily removed] 40.733812            -73.980544                    1
                   1 Ave & E 5 St                        40.725864            -73.986389                    1
                   1 Ave & E 62 St                       40.761227            -73.960940                    8
                   1 Ave & E 68 St                       40.765005            -73.958185                   11
                   1 Ave & E 78 St                       40.771404            -73.953517                    8
                   1 Ave & E 94 St                       40.781721            -73.945940                   16
                   1 Pl & Clinton St                     40.680959            -73.999057                    1
                   12 Ave & W 125 St                     40.818299            -73.960405                    3
                   12 Ave & W 40 St                      40.760875            -74.002777                    1

                                                                                                     start station id  \
start station name end station name                      end station latitude end station longitude
1 Ave & E 110 St   1 Ave & E 110 St                      40.792327            -73.938300                          200
                   1 Ave & E 18 St [temporarily removed] 40.733812            -73.980544                            1
                   1 Ave & E 5 St                        40.725864            -73.986389                            1
                   1 Ave & E 62 St                       40.761227            -73.960940                            8
                   1 Ave & E 68 St                       40.765005            -73.958185                           11
                   1 Ave & E 78 St                       40.771404            -73.953517                            8
                   1 Ave & E 94 St                       40.781721            -73.945940                           16
                   1 Pl & Clinton St                     40.680959            -73.999057                            1
                   12 Ave & W 125 St                     40.818299            -73.960405                            3
                   12 Ave & W 40 St                      40.760875            -74.002777                            1

                                                                                                     start station latitude  \
start station name end station name                      end station latitude end station longitude
1 Ave & E 110 St   1 Ave & E 110 St                      40.792327            -73.938300                                200
                   1 Ave & E 18 St [temporarily removed] 40.733812            -73.980544                                  1
                   1 Ave & E 5 St                        40.725864            -73.986389                                  1
                   1 Ave & E 62 St                       40.761227            -73.960940                                  8
                   1 Ave & E 68 St                       40.765005            -73.958185                                 11
                   1 Ave & E 78 St                       40.771404            -73.953517                                  8
                   1 Ave & E 94 St                       40.781721            -73.945940                                 16
                   1 Pl & Clinton St                     40.680959            -73.999057                                  1
                   12 Ave & W 125 St                     40.818299            -73.960405                                  3
                   12 Ave & W 40 St                      40.760875            -74.002777                                  1

                                                                                                     start station longitude  \
start station name end station name                      end station latitude end station longitude
1 Ave & E 110 St   1 Ave & E 110 St                      40.792327            -73.938300                                 200
                   1 Ave & E 18 St [temporarily removed] 40.733812            -73.980544                                   1
                   1 Ave & E 5 St                        40.725864            -73.986389                                   1
                   1 Ave & E 62 St                       40.761227            -73.960940                                   8
                   1 Ave & E 68 St                       40.765005            -73.958185                                  11
                   1 Ave & E 78 St                       40.771404            -73.953517                                   8
                   1 Ave & E 94 St                       40.781721            -73.945940                                  16
                   1 Pl & Clinton St                     40.680959            -73.999057                                   1
                   12 Ave & W 125 St                     40.818299            -73.960405                                   3
                   12 Ave & W 40 St                      40.760875            -74.002777                                   1

                                                                                                     end station id  \
start station name end station name                      end station latitude end station longitude
1 Ave & E 110 St   1 Ave & E 110 St                      40.792327            -73.938300                        200
                   1 Ave & E 18 St [temporarily removed] 40.733812            -73.980544                          1
                   1 Ave & E 5 St                        40.725864            -73.986389                          1
                   1 Ave & E 62 St                       40.761227            -73.960940                          8
                   1 Ave & E 68 St                       40.765005            -73.958185                         11
                   1 Ave & E 78 St                       40.771404            -73.953517                          8
                   1 Ave & E 94 St                       40.781721            -73.945940                         16
                   1 Pl & Clinton St                     40.680959            -73.999057                          1
                   12 Ave & W 125 St                     40.818299            -73.960405                          3
                   12 Ave & W 40 St                      40.760875            -74.002777                          1

                                                                                                     bikeid  \
start station name end station name                      end station latitude end station longitude
1 Ave & E 110 St   1 Ave & E 110 St                      40.792327            -73.938300                200
                   1 Ave & E 18 St [temporarily removed] 40.733812            -73.980544                  1
                   1 Ave & E 5 St                        40.725864            -73.986389                  1
                   1 Ave & E 62 St                       40.761227            -73.960940                  8
                   1 Ave & E 68 St                       40.765005            -73.958185                 11
                   1 Ave & E 78 St                       40.771404            -73.953517                  8
                   1 Ave & E 94 St                       40.781721            -73.945940                 16
                   1 Pl & Clinton St                     40.680959            -73.999057                  1
                   12 Ave & W 125 St                     40.818299            -73.960405                  3
                   12 Ave & W 40 St                      40.760875            -74.002777                  1

                                                                                                     usertype  \
start station name end station name                      end station latitude end station longitude
1 Ave & E 110 St   1 Ave & E 110 St                      40.792327            -73.938300                  200
                   1 Ave & E 18 St [temporarily removed] 40.733812            -73.980544                    1
                   1 Ave & E 5 St                        40.725864            -73.986389                    1
                   1 Ave & E 62 St                       40.761227            -73.960940                    8
                   1 Ave & E 68 St                       40.765005            -73.958185                   11
                   1 Ave & E 78 St                       40.771404            -73.953517                    8
                   1 Ave & E 94 St                       40.781721            -73.945940                   16
                   1 Pl & Clinton St                     40.680959            -73.999057                    1
                   12 Ave & W 125 St                     40.818299            -73.960405                    3
                   12 Ave & W 40 St                      40.760875            -74.002777                    1

                                                                                                     birth year  \
start station name end station name                      end station latitude end station longitude
1 Ave & E 110 St   1 Ave & E 110 St                      40.792327            -73.938300                    200
                   1 Ave & E 18 St [temporarily removed] 40.733812            -73.980544                      1
                   1 Ave & E 5 St                        40.725864            -73.986389                      1
                   1 Ave & E 62 St                       40.761227            -73.960940                      8
                   1 Ave & E 68 St                       40.765005            -73.958185                     11
                   1 Ave & E 78 St                       40.771404            -73.953517                      8
                   1 Ave & E 94 St                       40.781721            -73.945940                     16
                   1 Pl & Clinton St                     40.680959            -73.999057                      1
                   12 Ave & W 125 St                     40.818299            -73.960405                      3
                   12 Ave & W 40 St                      40.760875            -74.002777                      1

                                                                                                     gender
start station name end station name                      end station latitude end station longitude
1 Ave & E 110 St   1 Ave & E 110 St                      40.792327            -73.938300                200
                   1 Ave & E 18 St [temporarily removed] 40.733812            -73.980544                  1
                   1 Ave & E 5 St                        40.725864            -73.986389                  1
                   1 Ave & E 62 St                       40.761227            -73.960940                  8
                   1 Ave & E 68 St                       40.765005            -73.958185                 11
                   1 Ave & E 78 St                       40.771404            -73.953517                  8
                   1 Ave & E 94 St                       40.781721            -73.945940                 16
                   1 Pl & Clinton St                     40.680959            -73.999057                  1
                   12 Ave & W 125 St                     40.818299            -73.960405                  3
                   12 Ave & W 40 St                      40.760875            -74.002777                  1

In [28]:
start_stop_0520_pos = cy_may20_df.groupby(["start station name","start station latitude","start station longitude"])
start_stop_0520_pos['start station name'].count().head(10)

start station name                     start station latitude  start station longitude
1 Ave & E 110 St                       40.792327               -73.938300                 1342
1 Ave & E 16 St [temporarily removed]  40.732219               -73.981656                 4434
1 Ave & E 18 St [temporarily removed]  40.733812               -73.980544                 4388
1 Ave & E 30 St                        40.741444               -73.975361                 3274
1 Ave & E 44 St                        40.750020               -73.969053                 2759
1 Ave & E 5 St                         40.725864               -73.986389                 2761
1 Ave & E 62 St                        40.761227               -73.960940                 4723
1 Ave & E 68 St                        40.765005               -73.958185                 8007
1 Ave & E 78 St                        40.771404               -73.953517                 4730
1 Ave & E 94 St                        40.781721               -73.945940                 2002
Name: start station name, dtype: int64

In [32]:
start_stop_0520_pos["start station name"].head(10)

0                             E 43 St & 2 Ave
1                             E 65 St & 2 Ave
2                  Lefferts Pl & Franklin Ave
3          Frederick Douglass Blvd & W 115 St
4                  Central Ave & Starr Street
                          ...
1440172              St. Ann's Ave & E 144 St
1443138              St. Ann's Ave & E 144 St
1458351              St. Ann's Ave & E 144 St
1473934              St. Ann's Ave & E 144 St
1474033              St. Ann's Ave & E 144 St
Name: start station name, Length: 9240, dtype: object

In [35]:
start_summary_df = pd.DataFrame(start_stop_0520_pos.count())

In [36]:
start_summary_df.head()

,,,tripduration,starttime,stoptime,start station id,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
start station name,start station latitude,start station longitude,,,,,,,,,,,,
1 Ave & E 110 St,40.792327,-73.938300,1342,1342,1342,1342,1342,1342,1342,1342,1342,1342,1342,1342
1 Ave & E 16 St [temporarily removed],40.732219,-73.981656,4434,4434,4434,4434,4434,4434,4434,4434,4434,4434,4434,4434
1 Ave & E 18 St [temporarily removed],40.733812,-73.980544,4388,4388,4388,4388,4388,4388,4388,4388,4388,4388,4388,4388
1 Ave & E 30 St,40.741444,-73.975361,3274,3274,3274,3274,3274,3274,3274,3274,3274,3274,3274,3274
1 Ave & E 44 St,40.750020,-73.969053,2759,2759,2759,2759,2759,2759,2759,2759,2759,2759,2759,2759

In [41]:
start_summary_df.to_csv('start_summary.csv')

In [45]:
start_end_summary_df = pd.DataFrame(start_stop_0520_group.count())

In [47]:
start_end_summary_df.to_csv('start_end_summary_2020.csv')

In [51]:
start_stop_0521_pos = cy_may21_df.groupby(["start_station_name","start_lat","start_lng"])
start_stop_0521_pos.count().head(10)

                                         ride_id  rideable_type  started_at  \
start_station_name start_lat start_lng
1 Ave & E 110 St   40.792327 -73.938300     2035           2035        2035
1 Ave & E 16 St    40.732218 -73.981655     7126           7126        7126
                   40.732219 -73.981656       40             40          40
1 Ave & E 18 St    40.733812 -73.980544     6006           6006        6006
1 Ave & E 30 St    40.741443 -73.975360     5023           5023        5023
                   40.741444 -73.975361       33             33          33
1 Ave & E 39 St    40.747140 -73.971130     7136           7136        7136
1 Ave & E 44 St    40.750019 -73.969053     2810           2810        2810
                   40.750020 -73.969053       42             42          42
1 Ave & E 6 St     40.726330 -73.986168     5686           5686        5686

                                         ended_at  start_station_id  \
start_station_name start_lat start_lng
1 Ave & E 110 St   40.792327 -73.938300      2035              2035
1 Ave & E 16 St    40.732218 -73.981655      7126              7126
                   40.732219 -73.981656        40                40
1 Ave & E 18 St    40.733812 -73.980544      6006              6006
1 Ave & E 30 St    40.741443 -73.975360      5023              5023
                   40.741444 -73.975361        33                33
1 Ave & E 39 St    40.747140 -73.971130      7136              7136
1 Ave & E 44 St    40.750019 -73.969053      2810              2810
                   40.750020 -73.969053        42                42
1 Ave & E 6 St     40.726330 -73.986168      5686              5686

                                         end_station_name  end_station_id  \
start_station_name start_lat start_lng
1 Ave & E 110 St   40.792327 -73.938300              2033            2033
1 Ave & E 16 St    40.732218 -73.981655              7096            7096
                   40.732219 -73.981656                40              40
1 Ave & E 18 St    40.733812 -73.980544              5995            5995
1 Ave & E 30 St    40.741443 -73.975360              5010            5010
                   40.741444 -73.975361                33              33
1 Ave & E 39 St    40.747140 -73.971130              7120            7120
1 Ave & E 44 St    40.750019 -73.969053              2808            2808
                   40.750020 -73.969053                42              42
1 Ave & E 6 St     40.726330 -73.986168              5680            5680

                                         end_lat  end_lng  member_casual
start_station_name start_lat start_lng
1 Ave & E 110 St   40.792327 -73.938300     2033     2033           2035
1 Ave & E 16 St    40.732218 -73.981655     7096     7096           7126
                   40.732219 -73.981656       40       40             40
1 Ave & E 18 St    40.733812 -73.980544     5995     5995           6006
1 Ave & E 30 St    40.741443 -73.975360     5010     5010           5023
                   40.741444 -73.975361       33       33             33
1 Ave & E 39 St    40.747140 -73.971130     7120     7120           7136
1 Ave & E 44 St    40.750019 -73.969053     2808     2808           2810
                   40.750020 -73.969053       42       42             42
1 Ave & E 6 St     40.726330 -73.986168     5680     5680           5686

In [53]:
start_summary21_df = pd.DataFrame(start_stop_0521_pos.count())
# start_summary21_df.head(10)
start_summary21_df.to_csv('start_summary_may2021.csv')

In [55]:
start_stop_0521_group = cy_may21_df.groupby(["start_station_name","end_station_name","end_lat","end_lng"])
# start_stop_0521_group.count().head(10)
start_end_summary21_df = pd.DataFrame(start_stop_0521_group.count())
start_end_summary21_df.to_csv('start_end_summary_may2021.csv')